### ISSUE TITLE
Add support for Letterboxd.com

### ISSUE THREAD

**Issue by pauff** [JayXon/MoreMovieRatings#11]
非常喜欢您的插件，作为重度使用者，想提一个建议，能否添加对另一个影迷体验更优秀的影视评价网站 https://letterboxd.com/ 的支持？也许 Letterboxd 并不如 IMDb 的名气大，但是其实它的用户数已经远远超过 IMDb，并且有更好的氛围体验。
以最近比较火的电影「M3GAN」为例，豆瓣有 17,620 人评价，IMDb 有 53,609 人，而 Letterboxd 已经有225,681 人了（截至2023-02-06 12:00）。
非常感谢！

**Comment by JayXon** [comment]
谢谢建议，在 Letterboxd 上面显示豆瓣和 IMDb 的评分应该比较好实现，但是如果想在豆瓣和 IMDb 上显示 Letterboxd 的评分则需要一个合适的 API。

不过我最近估计不会有时间做这个，如果你有需求欢迎提交 PR，脚本很简单，有现成的函数可以调用豆瓣和 IMDb 的评分。

**Comment by pauff** [comment]
感谢回复，可惜我还不会写脚本代码😂 您能考虑就已经很感谢了！

**Comment by JayXon** [comment]
新版添加了 Letterboxd 的支持，不过没有豆瓣评分分布的数据，所以显示的分布是 Letterboxd 的，目前没什么好办法。

如果有其他问题欢迎反馈。
