### ISSUE TITLE
豆瓣影人页面改版，请求支持imdb链接

### ISSUE THREAD

**Issue by ningsibuqu** [JayXon/MoreMovieRatings#12]
https://www.douban.com/personage/27480351/
![image](https://github.com/JayXon/MoreMovieRatings/assets/51028975/4024fc22-f2c5-4185-beea-ac09ce06fa2b)
现在影人页变这样了 IMDb编号 不能点进去了，请求支持一下

**Comment by ningsibuqu** [comment]
@JayXon 大佬可以看看吗，感谢。

**Comment by JayXon** [comment]
试试 0.7.3
