### ISSUE TITLE
豆瓣评分失效，会不会跟豆瓣取消 IMDB 关联有关？

### ISSUE THREAD

**Issue by ningsibuqu** [JayXon/MoreMovieRatings#8]
imdb 看 豆瓣 还可以。
https://www.imdb.com/title/tt2495118/
豆瓣看 imdb 失效
https://movie.douban.com/subject/10794042/

**Comment by JayXon** [comment]
谢谢报告，确实是这个原因，0.6.6修复了，并且还把IMDb链接也一并恢复了

**Comment by ningsibuqu** [comment]
> 谢谢报告，确实是这个原因，0.6.6修复了，并且还把IMDb链接也一并恢复了

https://movie.douban.com/subject/1929995/

发现这部 imdb 超链接失效？
![image](https://user-images.githubusercontent.com/51028975/136170256-b7add2c2-d00b-48e8-9001-9d630b321090.png)

**Comment by JayXon** [comment]
谢谢报告，是因为这个条目的官方网站那里填了IMDb网址冲突了，0.6.8修复了此问题
